USE VOLKOV	
DECLARE @fio VARCHAR(50), @bt DATE
DECLARE @cur_date DATE
DECLARE dbc CURSOR LOCAL FORWARD_ONLY STATIC
FOR SELECT FIO, BIRTHDAY 
FROM Student

DECLARE @mess VARCHAR(50)
SET @cur_date = '02/07/1998'
OPEN dbc
	FETCH NEXT FROM dbc INTO @fio, @bt
	WHILE @@FETCH_STATUS = 0
BEGIN
	IF @bt BETWEEN DATEADD(MONTH,-1, @cur_date) AND DATEADD(MONTH,1,@cur_date)
	BEGIN
		SET @mess = @fio+'    '+CAST(@bt AS VARCHAR(11))
		PRINT @mess
	END
	FETCH NEXT FROM dbc INTO @fio, @bt
END
CLOSE dbc
DEALLOCATE dbc